### ISSUE TITLE
Actualizar documento IEEE830

### ISSUE THREAD

**Issue by Vargas-Veronica** [Web-Developers2-0/ProyectoIntegrador2#1]
Actualizar Documento IEEE 830
[IEEE 830 - https://docs.google.com/document/d/1OTZqcQ7kBufLyFaoEgPfZDuX9d0T4nI3xecdMYuw5TU/edit

**Comment by emirobles** [comment]
Queda actualizado el documentado, se agregan las observaciones marcadas en el Sprint 0, y se actualiza con la información del Sprint 1
