### ISSUE TITLE
#US2 Como desarrollador Necesito implementar un dashboard personalizador  para mostrar y poder actualizar los datos del usuario

### ISSUE THREAD

**Issue by Vargas-Veronica** [Web-Developers2-0/ProyectoIntegrador2#10]
> Visualización de datos personalizados
> Modificación de datos personalizados
> Historial y seguimiento de pedidos

**Comment by escuelamedia** [comment]
#US1 #TSK2 Gestionar la autenticación utilizando técnicas seguras como JSON Web Tokens (JWT) y crear endpoints necesarios en el servidor para manejar las solicitudes de datos del usuario y su historial de pedidos.

**Comment by escuelamedia** [comment]
#US2 #TSK2 Conectar el frontend con el backend para enviar solicitudes al servidor y recibir los datos necesarios, utilizando tecnologías como AJAX o Fetch API, y actualiza dinámicamente la interfaz de usuario con JavaScript.
