### ISSUE TITLE
#US1 #TSK7 Crear landing page para la sección de inicio (home.component)

### ISSUE THREAD

**Issue by alanapolitana** [Web-Developers2-0/ProyectoIntegrador2#15]

**Comment by alanapolitana** [comment]
Hacer carrousel botones y reseñas

**Comment by escuelamedia** [comment]
!-- Carrusel -->
    <section>
      <div class="container-carousel">
        <div class="carruseles" id="slider">
          <section class="slider-section">
            <img src="front/images/SuscribeteCarousel.jpeg" />
          </section>

          <section class="slider-section">
            <img src="front/images/SpiderCarousel.jpeg" />
          </section>

          <section class="slider-section">
            <img src="front/images/EnviosCarousel.jpeg" />
          </section>
          <section class="slider-section">
            <img src="front/images/CapitanCarousel.jpeg" />
          </section>
        </div>
        <div class="btn-left"><i class="bx bx-chevron-left"></i></div>
        <div class="btn-right"><i class="bx bx-chevron-right"></i></div>
      </div>
    </section>
    
    <section id="banner">
      <div class="container">
        <div class="button">
          <img
            src="front/images/free.png"
            alt="Envío_gratis_Córdoba_capital"
          />
          <p class="button-text">Envío gratis Córdoba capital</p>
        </div>
        <div class="button">
          <img
            src="front/images/tarjetas.png"
            alt="Todos_los_medios_de_pago"
          />
          <p class="button-text">Todos los medios de pago</p>
        </div>
        <div class="button">
          <img src="front/images/30dto.png" alt="Descuentos_Exclusivos" />
          <p class="button-text">Descuentos Exclusivos</p>
        </div>
      </div>
    </section>

    
    <section id="reseñas">
      <div class="review-title">
        <h1>Reseñas</h1>
      </div>

      <div class="reseña_container">
        <div class="reseña_card">
          <div class="top">
            <img src="front/images/estrella.jpg" alt="estrellas" />
            <p>
              Excelente atención, necesitaba hacer un regalo y me llegaron los
              cómics el mismo día. Muy recomendado.
            </p>
          </div>
          <div class="bottom">
            <img src="front/images/juan.jpg" alt="User" />
            <h2>JUAN</h2>
          </div>
        </div>

        <div class="reseña_card">
          <div class="top">
            <img src="front/images/estrella.jpg" alt="estrellas" />
            <p>
              La selección de cómics es impresionante, ¡nunca dejo de
              sorprenderme con lo que encuentro!
            </p>
          </div>
          <div class="bottom">
            <img src="front/images/Maria.jpg" alt="User" />
            <h2>MARIA</h2>
          </div>
        </div>

        <div class="reseña_card">
          <div class="top">
            <img src="front/images/estrella.jpg" alt="estrellas" />
            <p>
              Esta tienda hace que mi niño interior se emocione cada vez que
              entro, ¡es un lugar único y mágico!
            </p>
          </div>
          <div class="bottom">
            <img src="front/images/Pilar.jpg" alt="User" />
            <h2>PILAR</h2>
          </div>
        </div>

        <div class="reseña_card">
          <div class="top">
            <img src="front/images/estrella.jpg" alt="estrellas" />
            <p>
              Los empleados son súper amables y conocedores, hacen que cada
              visita sea una experiencia genial.
            </p>
          </div>
          <div class="bottom">
            <img src="front/images/Lautaro.jpg" alt="User" />
            <h2>LAUTARO</h2>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </section>

**Comment by escuelamedia** [comment]
<section>
      <div class="container-carousel">
        <div class="carruseles" id="slider">
          <section class="slider-section">
            <img src="front/images/SuscribeteCarousel.jpeg" />
          </section>

          <section class="slider-section">
            <img src="front/images/SpiderCarousel.jpeg" />
          </section>

          <section class="slider-section">
            <img src="front/images/EnviosCarousel.jpeg" />
          </section>
          <section class="slider-section">
            <img src="front/images/CapitanCarousel.jpeg" />
          </section>
        </div>
        <div class="btn-left"><i class="bx bx-chevron-left"></i></div>
        <div class="btn-right"><i class="bx bx-chevron-right"></i></div>
      </div>
    </section>
    
    <section id="banner">
      <div class="container">
        <div class="button">
          <img
            src="front/images/free.png"
            alt="Envío_gratis_Córdoba_capital"
          />
          <p class="button-text">Envío gratis Córdoba capital</p>
        </div>
        <div class="button">
          <img
            src="front/images/tarjetas.png"
            alt="Todos_los_medios_de_pago"
          />
          <p class="button-text">Todos los medios de pago</p>
        </div>
        <div class="button">
          <img src="front/images/30dto.png" alt="Descuentos_Exclusivos" />
          <p class="button-text">Descuentos Exclusivos</p>
        </div>
      </div>
    </section>

**Comment by emirobles** [comment]
Completado
