### ISSUE TITLE
#US10 #TSK9 Configuracion backend (django entorno virtual y app)

### ISSUE THREAD

**Issue by alanapolitana** [Web-Developers2-0/ProyectoIntegrador2#18]

**Comment by alanapolitana** [comment]
Logra vincular los modelos al Admin de Django, para poder realizar un CRUD.
Logra crear un superusuario para poder acceder al Admin.
Logra configurar la conexión al motor de base de datos a usar.
Logra informar las credenciales de acceso del superusuario.

**Comment by emirobles** [comment]
Completado
