### ISSUE TITLE
Edición de la Wiki y documentación de ceremonias

### ISSUE THREAD

**Issue by Vargas-Veronica** [Web-Developers2-0/ProyectoIntegrador2#2]

**Comment by emirobles** [comment]
Se actualiza la documentación de ceremonias: https://docs.google.com/document/d/1NsqsSH8VUzVKMvltRijQ6uUFr5Jamaxt0znUh3jaipU/edit

**Comment by emirobles** [comment]
Queda actualizada la Wiki y se agrega lo ultimo referido a la Sprint Review por el cierre del Sprint 1
