### ISSUE TITLE
#US1 Se requiere una nueva UI para la e commerce e incorporar un dashboard personalizado para el usuario pueda ver su historial de compras.  

### ISSUE THREAD

**Issue by 1pame** [Web-Developers2-0/ProyectoIntegrador2#38]
#40

**Comment by 1pame** [comment]
#US1 #TSK2 Diseñar la interfaz de usuario (UI) utilizando HTML, CSS  y el framework de frontend Angular (adaptar a ts el codigo js).

**Comment by 1pame** [comment]
#US1 #TSK3 Incorporar al Dashboard una tabla en donde se muestre el historial de compras del usuario

**Comment by 1pame** [comment]
#US1 #TSK4 Incluir en el Dashboard un baner que muestre al usuario y un boton para cerrar sesión

**Comment by 1pame** [comment]
#41

**Comment by 1pame** [comment]
#42

**Comment by 1pame** [comment]
#43

**Comment by emirobles** [comment]
Completado
