### ISSUE TITLE
#US3 #TSK2 Las cards de productos deben contener el detalle de cada producto: dimensiones del comic, cantidad de páginas, autor/es, edición

### ISSUE THREAD

**Issue by 1pame** [Web-Developers2-0/ProyectoIntegrador2#48]

**Comment by emirobles** [comment]
Se crea modelo generico para la card de details product. El componente tiene todos los detalles solicitados para este Sprint1.
En el proximo Sprint2 se trabajara con el contenido para que sea personalizado segun el Producto al que ingresa el usuario.
