### ISSUE TITLE
#US8 Como cliente necesito que se implemente un carrito dinámico para las compras para facilitar la continuidad del proceso de compra

### ISSUE THREAD

**Issue by Vargas-Veronica** [Web-Developers2-0/ProyectoIntegrador2#8]
-  Diseño y desarrollo de interfaz (responsive)
-  CRUD de productos 
-  Persistencia de datos en la base de datos
-  Local storage (productos , subtotal,total)
-  Manejo de sesión
-  Opciones de pago

**Comment by 1pame** [comment]
#9
